POST http://localhost:3333/register
Content-Type: application/json

{
  "email": "tiago@tiago.com",
  "password": "123456"
}
###

POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "tiago@tiago.com",
  "password": "12094546Lp$"
}

###
GET http://localhost:3333/gasto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjExYzhiMmRmNGM1NTlkMjhjOWRlNWQ0MTAxNDFiMzBkOWUyYmNlM2IiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbW9uZXktbWFuYWdlci0zY2UyNSIsImF1ZCI6Im1vbmV5LW1hbmFnZXItM2NlMjUiLCJhdXRoX3RpbWUiOjE3MjQ5MDY0NDIsInVzZXJfaWQiOiJPbUljamtBdWtGWHRaUG9KZTNEWlBCbTlBaUcyIiwic3ViIjoiT21JY2prQXVrRlh0WlBvSmUzRFpQQm05QWlHMiIsImlhdCI6MTcyNDkwNjQ0MiwiZXhwIjoxNzI0OTEwMDQyLCJlbWFpbCI6InRpYWdvbG9wZXNjLmRldkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGlhZ29sb3Blc2MuZGV2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.r4BsE41IzPbtFT9uoOeZ5YIPPWBHLodbeNARZW7zoH3oIymC71PeOfwK5-GZJqFuk0IiO06dUH7ffDPpNl-Bwe4kAHu9m8Z_k7EHcU7BVWOt02pJvJaaLILbjOFqUTS7SjW-VB6v89LiutcYZ2tjPMQlp1j06JIFJ_2ssmwiWyexnf3WjqZCSStG8Nuxy2Y_59l7_X_6Ag7Yoi1BO-Adj4PaOEJ7Gqn6vi6aaA_OXxo8IkU5_Fk4VIgwEsurqHeif1G_IEks0riycCXZaiBxQ-_WqhVbhhlMHDOABZ9giuMqdJ25lLOsFnBcH6rBNIaVjydAwTIS5ijJhPG4L-45pg

###
GET http://localhost:3333/gasto/7137a9df-57d2-4c0d-bc35-9160caefcaf7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFkYmUwNmI1ZDdjMmE3YzA0NDU2MzA2MWZmMGZlYTM3NzQwYjg2YmMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbW9uZXktbWFuYWdlci0zY2UyNSIsImF1ZCI6Im1vbmV5LW1hbmFnZXItM2NlMjUiLCJhdXRoX3RpbWUiOjE3MjMwMDQwMTgsInVzZXJfaWQiOiJBNHZVeFVySHZXVUNWZDlXWjVhelNuR1lmUHoxIiwic3ViIjoiQTR2VXhVckh2V1VDVmQ5V1o1YXpTbkdZZlB6MSIsImlhdCI6MTcyMzAwNDAxOCwiZXhwIjoxNzIzMDA3NjE4LCJlbWFpbCI6InRpYWdvQHRpYWdvLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0aWFnb0B0aWFnby5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.rRhlOl-xZoCxqUWbB_Ui6vMcd9f6aqgoshna3syiXDtdf6rDULy2jJMDucqSNh4RAl-XK0HbjVthhaDcl6c69u1NCTgsq0zb-UJVSbpjzzOSJV4WyHhT6xNxjaKEbwheLBjm9IoVHfnFblI-GctOrXrDIINCQzZQ8G_-E3wD4XeaUeNYh74B2FLtmHT3V_Zdjd37viGsaiyX3-K6y8FwTBkbbBHcPGT03obfHUkSqW6DIcbypA91euCbmBuc2Zaz1J7Tq4cXkQF6X4L4JmKXMYZ8QnkqYJR1X-cNvW6sej2v9cVqMBENMcItp8N-_Acgi6gugxoIC-bictemJrwY6Q

###
POST http://localhost:3333/gasto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjExYzhiMmRmNGM1NTlkMjhjOWRlNWQ0MTAxNDFiMzBkOWUyYmNlM2IiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbW9uZXktbWFuYWdlci0zY2UyNSIsImF1ZCI6Im1vbmV5LW1hbmFnZXItM2NlMjUiLCJhdXRoX3RpbWUiOjE3MjQ5MDY0NDIsInVzZXJfaWQiOiJPbUljamtBdWtGWHRaUG9KZTNEWlBCbTlBaUcyIiwic3ViIjoiT21JY2prQXVrRlh0WlBvSmUzRFpQQm05QWlHMiIsImlhdCI6MTcyNDkwNjQ0MiwiZXhwIjoxNzI0OTEwMDQyLCJlbWFpbCI6InRpYWdvbG9wZXNjLmRldkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGlhZ29sb3Blc2MuZGV2QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.r4BsE41IzPbtFT9uoOeZ5YIPPWBHLodbeNARZW7zoH3oIymC71PeOfwK5-GZJqFuk0IiO06dUH7ffDPpNl-Bwe4kAHu9m8Z_k7EHcU7BVWOt02pJvJaaLILbjOFqUTS7SjW-VB6v89LiutcYZ2tjPMQlp1j06JIFJ_2ssmwiWyexnf3WjqZCSStG8Nuxy2Y_59l7_X_6Ag7Yoi1BO-Adj4PaOEJ7Gqn6vi6aaA_OXxo8IkU5_Fk4VIgwEsurqHeif1G_IEks0riycCXZaiBxQ-_WqhVbhhlMHDOABZ9giuMqdJ25lLOsFnBcH6rBNIaVjydAwTIS5ijJhPG4L-45pg

{"title":"ssjdjd","price":"646446","description":"ggrgrgrg","category":"Entrada"}

###
PUT http://localhost:3333/gasto/7137a9df-57d2-4c0d-bc35-9160caefcaf7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFkYmUwNmI1ZDdjMmE3YzA0NDU2MzA2MWZmMGZlYTM3NzQwYjg2YmMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbW9uZXktbWFuYWdlci0zY2UyNSIsImF1ZCI6Im1vbmV5LW1hbmFnZXItM2NlMjUiLCJhdXRoX3RpbWUiOjE3MjMwMDQwMTgsInVzZXJfaWQiOiJBNHZVeFVySHZXVUNWZDlXWjVhelNuR1lmUHoxIiwic3ViIjoiQTR2VXhVckh2V1VDVmQ5V1o1YXpTbkdZZlB6MSIsImlhdCI6MTcyMzAwNDAxOCwiZXhwIjoxNzIzMDA3NjE4LCJlbWFpbCI6InRpYWdvQHRpYWdvLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0aWFnb0B0aWFnby5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.rRhlOl-xZoCxqUWbB_Ui6vMcd9f6aqgoshna3syiXDtdf6rDULy2jJMDucqSNh4RAl-XK0HbjVthhaDcl6c69u1NCTgsq0zb-UJVSbpjzzOSJV4WyHhT6xNxjaKEbwheLBjm9IoVHfnFblI-GctOrXrDIINCQzZQ8G_-E3wD4XeaUeNYh74B2FLtmHT3V_Zdjd37viGsaiyX3-K6y8FwTBkbbBHcPGT03obfHUkSqW6DIcbypA91euCbmBuc2Zaz1J7Tq4cXkQF6X4L4JmKXMYZ8QnkqYJR1X-cNvW6sej2v9cVqMBENMcItp8N-_Acgi6gugxoIC-bictemJrwY6Q

{
  "gasto": {
    "title": "Pichau 3 = editado",
    "category": 1,
    "price": "27,90",
    "description": "Teclado gamer Redragon",
    "createdAt": "31/07/2024"
  }
}

###
DELETE http://localhost:3333/gasto/71dfd8b3-ad8f-47b3-ab9b-9443de9e0eaa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFkYmUwNmI1ZDdjMmE3YzA0NDU2MzA2MWZmMGZlYTM3NzQwYjg2YmMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbW9uZXktbWFuYWdlci0zY2UyNSIsImF1ZCI6Im1vbmV5LW1hbmFnZXItM2NlMjUiLCJhdXRoX3RpbWUiOjE3MjMwMDQwMTgsInVzZXJfaWQiOiJBNHZVeFVySHZXVUNWZDlXWjVhelNuR1lmUHoxIiwic3ViIjoiQTR2VXhVckh2V1VDVmQ5V1o1YXpTbkdZZlB6MSIsImlhdCI6MTcyMzAwNDAxOCwiZXhwIjoxNzIzMDA3NjE4LCJlbWFpbCI6InRpYWdvQHRpYWdvLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0aWFnb0B0aWFnby5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.rRhlOl-xZoCxqUWbB_Ui6vMcd9f6aqgoshna3syiXDtdf6rDULy2jJMDucqSNh4RAl-XK0HbjVthhaDcl6c69u1NCTgsq0zb-UJVSbpjzzOSJV4WyHhT6xNxjaKEbwheLBjm9IoVHfnFblI-GctOrXrDIINCQzZQ8G_-E3wD4XeaUeNYh74B2FLtmHT3V_Zdjd37viGsaiyX3-K6y8FwTBkbbBHcPGT03obfHUkSqW6DIcbypA91euCbmBuc2Zaz1J7Tq4cXkQF6X4L4JmKXMYZ8QnkqYJR1X-cNvW6sej2v9cVqMBENMcItp8N-_Acgi6gugxoIC-bictemJrwY6Q
